### ISSUE TITLE
[Request] Resting based on condition

### ISSUE THREAD

**Issue by Vestium-R** [fantasycalendar/FoundryVTT-RestRecovery#101]
**Is your feature request related to a problem? Please describe.**
It would be amazing if there is a way to check for effects on an actor and "prevent" rests based on certain conditions. I currently have to manually check if someone has this condition and "rest" them in a manual way without the module. 

IE: With my nightmare effect I have the user roll a constitution save. If they pass they rest as per normal - if they fail they do not "rest". 

**Describe the solution you'd like**
Basic: I would like to be able to manage (or at least prevent / remind) the DM / player of their effect and that because of X effect they cannot rest. 

Advanced: I would like to be able to manage the effect and check what sort of rest they are able to get. IE: Are they able to spend hit dice, do they automatically get exhaustion because they didn't get to rest, do they only recover partially

Some high level thoughts:

When an actor has an effect named X - check the label and determine (maybe from a pre-defined template?) what parts of the rest they do not get or what needs to happen for them to rest (DC X check, etc). 

**Describe alternatives you've considered**
This is currently done manually

**Comment by bkis1** [comment]
I wanted to voice that I too would love to see something like this.  Specifically, can't short rest without water and can't long rest without food.

**Comment by Haxxer** [comment]
This will probably not be done anytime soon unless someone else makes a submission or pull request to this open source module. I lack the interest to do it mostly because I myself have very little use for these features, and I tend to mostly develop towards what my own virtual tabletop needs are.

However, these things are more than possible to be done with world hooks, especially since the DND5e system added `dnd5e.preLongRest` and `dnd5epreShortRest` hooks that you could use to prevent the rest from even starting in the first place. I would recommend asking in the Foundry discord whether someone can help you with this.

**Comment by Haxxer** [comment]
Added in 1.4.2, thanks for your contribution @sasquach45932!
