### ISSUE TITLE
[Request] v10 compatibility

### ISSUE THREAD

**Issue by tagnullde** [fantasycalendar/FoundryVTT-RestRecovery#84]
Hello :)

are there plans or a timeline you can share around v10 compatibility?

Regards
x41

**Comment by Haxxer** [comment]
Added in 1.3.0

**Comment by tagnullde** [comment]
Wow that was quick. Thank you so much. Love this module.

**Comment by benbarbour** [comment]
I think you still need to update the manifest to the new format so it stops being flagged in foundry as incompatible. Something like (from https://foundryvtt.com/article/module-development/):

```
  "compatibility": {
    "minimum": "9",
    "verified": "10"
  }
```

**Comment by Haxxer** [comment]
The currently released version is not compatible with V9, though - only V10. Adding that would make the latest released version installable on V9, which would not work.

**Comment by benbarbour** [comment]
Sorry, I should've been more clear, and more careful when I copy/pasted that example. Foundry v10 currently flags this module as "compatibility unknown". This is a better reference doc: https://foundryvtt.com/article/manifest-migration-guide/. In short though, you need to replace this:

```json
"minimumCoreVersion": "10",
"compatibleCoreVersion": "10",
```

with this:

```json
"compatibility": {
  "minimum": "10",
  "verified": "10"
}
```

or keep both so that v9 can read the `minimumCoreVersion` and `compatibleCoreVersion` version keys and note that it's incompatible with them.
